Overall Process

    Reading Source Data and Preprocessing
    Data formatting
    Scaling
    Split the data into Train and test
    Create & Compile model
    Train
    Predict
    Error metrics



In [ ]:
#import all necessary libraries
import os
import re
import numpy as np
import pandas as pd
import glob
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix



In [ ]:
#Mount google drive
from google.colab import drive
drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


Reading source data and preprocessing

In [ ]:
#read Phenotype metadata file from drive
df = pd.read_csv('/content/gdrive/My Drive/ResearchProject/dat/Phenotypes/Phenotypic_V1_0b_preprocessed1.csv')
replacement= {'FIQ': -99999,'VIQ': -99999,'PIQ': -99999}
df.fillna(value=replacement, inplace = True)
#df

#df['FIQ','VIQ','PIQ'] = df['FIQ','VIQ','PIQ'].fillna(-9999, inplace = True)

In [ ]:
#keep only necessary columns
df1 = df[['SUB_ID','SEX','FIQ','VIQ','PIQ','DX_GROUP']]
#df1



In [ ]:
df1.shape

(1112, 6)

In [ ]:
#read ROI = Region of Interest data file
dir="/content/gdrive/My Drive/ResearchProject/dat/rois_cc200"
files = glob.glob(dir + '/*cc200.1D')
#files = glob.glob(dir + '/Olin*rois_cc200.1D')

df_list = []

for filename in files:
    print(filename)
    df = pd.read_csv(filename,delimiter='\t')
    #add SUB_ID column to the dataframe, based on name of the file
    #df['SUB_ID'] = os.path.basename(filename)[10:15]
    
    
    #TODO: make this clean/simple
    x = re.findall(r'(?<!\d)(\d{7})(?!\d)', filename)
    x = x[0]
    x = x[2:]
    
    df['SUB_ID'] = x
    df_list.append(df)

frame = pd.concat(df_list, axis=0, ignore_index=True)


print(frame)






/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050040_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050041_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050042_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050043_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050044_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050045_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050046_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050047_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050048_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050049_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050050_rois_cc200.1D
/content/gdrive/My Drive/ResearchProject/dat/rois_cc200/Pitt_0050051_rois_cc200.1D
/con

In [ ]:

data_df1 = frame.apply(lambda x: pd.to_numeric(x, errors='coerce'))
#data_df1.head(2)


In [ ]:
#merge phenotype data frame with actual dataframe inorder to get additional columns merged
merged = pd.merge(data_df1,df1, left_on='SUB_ID',right_on='SUB_ID',how='inner')
merged.drop('SUB_ID', axis=1, inplace=True)
merged
#merged.shape

#1         #2         #3  ...    VIQ    PIQ  DX_GROUP
0       -2.527179   0.651299   6.139805  ...  109.0  108.0         2
1       -0.672059  -3.709695  14.256647  ...  109.0  108.0         2
2        1.786198 -10.780776  23.152732  ...  109.0  108.0         2
3        3.450363 -17.369489  28.938699  ...  109.0  108.0         2
4        3.992625 -19.678134  27.806023  ...  109.0  108.0         2
...           ...        ...        ...  ...    ...    ...       ...
201316  -4.056751 -23.438276 -30.229666  ...  110.0  123.0         2
201317 -16.021873 -13.524682  -8.380161  ...  110.0  123.0         2
201318 -30.028034  -1.152438  16.423056  ...  110.0  123.0         2
201319 -36.727993   8.714374  33.393784  ...  110.0  123.0         2
201320 -31.653923  12.934955  36.586625  ...  110.0  123.0         2

[201321 rows x 205 columns]

In [ ]:
# temporarily store classifciation variable to skip from scaling
classification_var = merged['DX_GROUP']

#print(classification_var)
#print(merged)

#scale the values between 0 and 1 using min max scaler
scaler=MinMaxScaler(feature_range=(0,1))
scaled_values= scaler.fit_transform(merged.drop('DX_GROUP', axis = 1))

#latch the non scaled classification variable to scaled dataset
merged = pd.DataFrame(scaled_values, index = merged.index)
merged['DX_GROUP'] = classification_var

scaled = np.array(merged)
#merged.head(2)
#print(scaled[:2,:])


In [ ]:
##splitting dataset into train and test (70-30)
train_data_percent = 0.70
training_size=int(len(scaled)*train_data_percent)
test_size=len(scaled)-training_size

#print(training_size,test_size)
train_data,test_data=scaled[0:training_size,:],scaled[training_size:len(scaled),:]
#print(train_data)
#print(test_data)

x_train,y_train=train_data[:,0:-1],train_data[:,-1]
print(x_train)
print(y_train)


x_test,y_test=test_data[:,0:-1],test_data[:,-1]
print(x_test.shape)
print(y_test.shape)



[[0.5471234  0.46303538 0.45055873 ... 0.99962056 0.99929127 0.99953072]
 [0.55001544 0.45870449 0.4625252  ... 0.99962056 0.99929127 0.99953072]
 [0.55384775 0.45168222 0.47564048 ... 0.99962056 0.99929127 0.99953072]
 ...
 [0.54563371 0.46783391 0.50323804 ... 0.99965051 0.9993312  0.99954071]
 [0.53831165 0.48151128 0.48444138 ... 0.99965051 0.9993312  0.99954071]
 [0.54529193 0.48663063 0.42736097 ... 0.99965051 0.9993312  0.99954071]]
[2. 2. 2. ... 2. 2. 2.]
(60397, 204)
(60397,)


In [ ]:
#check the shape
print(x_train.shape), print(y_train.shape)

(140924, 204)
(140924,)


(None, None)

In [ ]:
#check the shape
print(x_test.shape), print(y_test.shape)

(60397, 204)
(60397,)


(None, None)

In [ ]:
#RandomForest model
model = RandomForestClassifier(n_estimators=50)
model.fit(x_train, y_train.ravel())

train_predict = model.predict(x_train)
test_predict = model.predict(x_test)
#print(train_predict)
#print(test_predict)

tn, fp, fn, tp  = confusion_matrix(y_test, test_predict, labels=[2, 1]).ravel()
print(tn, fp, fn, tp)

accuracy = (tp+tn)/(tp+tn+fp+fn)
specificity = tn/(fp+tn)
precision = tp/(tp+fp)
recall = tp/(tp+fn)
fscore = 2*tp/(2*tp+fp+fn)

print(accuracy)
print(specificity)
print(precision)
print(recall)
print(fscore)



14443 22027 8672 15255
0.4917131645611537
0.3960241294214423
0.40917869213025054
0.6375642579512685
0.4984561093956771


In [ ]:
# Logistic regression
model1 = LogisticRegression()
model1.fit(x_train, y_train.ravel())

#train_predict1 = model1.predict(x_train)
test_predict1 = model1.predict(x_test)
tn1, fp1, fn1, tp1  = confusion_matrix(y_test, test_predict1, labels=[2, 1]).ravel()
print(tn1, fp1, fn1, tp1)

accuracy1 = (tp1+tn1)/(tp1+tn1+fp1+fn1)
specificity1 = tn1/(fp1+tn1)
precision1 = tp1/(tp1+fp1)
recall1 = tp1/(tp1+fn1)
fscore1 = 2*tp1/(2*tp1+fp1+fn1)

print(accuracy1)
print(specificity1)
print(precision1)
print(recall1)
print(fscore1)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


5236 31234 3626 20301
0.4228190141894465
0.1435700575815739
0.3939264577471621
0.8484557194800852
0.5380456388645941


In [ ]:
# Support vector machine (linear kernel)
model2 = LinearSVC()
model2.fit(x_train, y_train.ravel())

#train_predict2 = model2.predict(x_train)
test_predict2 = model2.predict(x_test)
tn2, fp2, fn2, tp2  = confusion_matrix(y_test, test_predict2, labels=[2, 1]).ravel()
print(tn2, fp2, fn2, tp2)

accuracy2 = (tp2+tn2)/(tp2+tn2+fp2+fn2)
specificity2 = tn2/(fp2+tn2)
precision2 = tp2/(tp2+fp2)
recall2 = tp2/(tp2+fn2)
fscore2 = 2*tp2/(2*tp2+fp2+fn2)

print(accuracy2)
print(specificity2)
print(precision2)
print(recall2)
print(fscore2)


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


5236 31234 3626 20301
0.4228190141894465
0.1435700575815739
0.3939264577471621
0.8484557194800852
0.5380456388645941


In [ ]:
# Support vector machine (polynomial kernel)
model3 = SVC(kernel="poly")
model3.fit(x_train, y_train.ravel())

#train_predict3 = model3.predict(x_train)
test_predict3 = model3.predict(x_test)
tn3, fp3, fn3, tp3  = confusion_matrix(y_test, test_predict3, labels=[2, 1]).ravel()
print(tn3, fp3, fn3, tp3)

accuracy3 = (tp3+tn3)/(tp3+tn3+fp3+fn3)
specificity3 = tn3/(fp3+tn3)
precision3 = tp3/(tp3+fp3)
recall3 = tp3/(tp3+fn3)
fscore3 = 2*tp3/(2*tp3+fp3+fn3)

print(accuracy3)
print(specificity3)
print(precision3)
print(recall3)
print(fscore3)

In [ ]:
# K nearest neighbors
model4 = KNeighborsClassifier()
model4.fit(x_train, y_train.ravel())

#train_predict4 = model4.predict(x_train)
test_predict4 = model4.predict(x_test)
tn4, fp4, fn4, tp4  = confusion_matrix(y_test, test_predict4, labels=[2, 1]).ravel()
print(tn4, fp4, fn4, tp4)

accuracy4 = (tp4+tn4)/(tp4+tn4+fp4+fn4)
specificity4 = tn4/(fp4+tn4)
precision4 = tp4/(tp4+fp4)
recall4 = tp4/(tp4+fn4)
fscore4 = 2*tp4/(2*tp4+fp4+fn4)

print(accuracy4)
print(specificity4)
print(precision4)
print(recall4)
print(fscore4)